# Generated by Django 4.2.24 on 2025-10-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_language_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
